### PR TITLE
Update to EF Core 9

### LINKED ISSUE #175: .NET 9 support

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #175

### CODE REVIEW

**Review by roji — APPROVED** [review]
Thanks @ErikEJ!

**Comment by ErikEJ** [comment]
Happy to push the package?

**Comment by roji** [comment]
Sure, I guess - we can always release a patch or minor version later if we do more stuff here.

**Comment by ErikEJ** [comment]
@roji Yes, I was hoping we could release a minor version when regex in Azure SQL finally goes GA

**Comment by roji** [comment]
@ErikEJ I think it's also fine to simply release the regex support now - before the Azure SQL feature goes GA. We can document the fact that it use a prerelease feature on the server side (we're doing that elsewhere for the new JSON and vector types).

**Comment by ErikEJ** [comment]
@roji Sounds great, in that case I would like someone to look at my PR 🙏

**Pull request merged**
